version: '3'
services:
  nginx:
    image: challenge3-nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    image: challenge3-node-service
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: challenge3-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
